services:
  database:
    build: .
    image: pokedex-postgres:16-custom
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER:-pokedex}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-pokedex_secret}
      POSTGRES_DB: ${PG_DATABASE:-pokedex}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
