services:
  database:
    build: .
    image: pokedex-mongo:7-custom
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-pokedex}

volumes:
  mongo-data:
